version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app         # ğŸ”¥ ì½”ë“œ ìˆ˜ì • ì¦‰ì‹œ ë°˜ì˜ë¨
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
